import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingstartedSidebar: [{ type: 'autogenerated', dirName: 'getting-started' }],
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  referencesSidebar: [{ type: 'autogenerated', dirName: 'references' }],
  moddingtoolsSidebar: [{ type: 'autogenerated', dirName: 'modding-tools' }],
  resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
  engineapiSidebar: [{ type: 'autogenerated', dirName: 'engine-api' }],
  scriptingapiSidebar: [{ type: 'autogenerated', dirName: 'scripting-docs' }],
  forcontributorsSidebar: [{ type: 'autogenerated', dirName: 'for-contributors' }],
};

export default sidebars;
