--[[ ----------------------------------------------------------------------------------------------
 : CS 1.5.10, CoP 1.6.02
  :      
 : 2013  Shoker Weapon Mod
    : Shoker, <...> 
 
 Shoker Weapon Mod 2.1 port, modified by Wang_Laoshi (Ethereal) to work with Anomaly mod. Thanks a lot to the original creators of this mod - Shoker,  and SWM Team in general.
--]] ----------------------------------------------------------------------------------------------

--[[
	TODO:
		*    ltx()  ini-          
		    system_ini()    ini,          
--]]

--************************************************************--
--***********************[ ]***********************--
--************************************************************--
local _SN = script_name()

--**************************************************************--
--********************[ ]********************--
--**************************************************************--

--\\   ""   ""   "" (Roll  )
--\\  malandrinus  														
function get_all_direction(dir)
	--* ""
	local dir_right = vector()
	dir_right:crossproduct(dir, vector():set(0,1,0))
	dir_right = dir_right:normalize()
	
	--* ""
	local dir_up = vector()
	dir_up:crossproduct(dir_right, dir)
	dir_up = dir_up:normalize()	
	
	return dir_right:invert(), dir_up
end

--\\           
--\\     (malandrinus)
function point_to_hud(point)
    local dev = device()
    local scr_w = dev.width
    local scr_h = dev.height

    local fov2 = (dev.fov/2) * (math.pi/180)
    local scr_dist = 0.5 * scr_h / math.tan(fov2)

    local ppp = vector():sub(point, dev.cam_pos)
    local dp = dev.cam_dir:dotproduct(ppp)

    local x = 512 + dev.cam_right:dotproduct(ppp) * scr_dist / dp * (1024/scr_w)
    local y = 384 - dev.cam_top:dotproduct(ppp)   * scr_dist / dp * (768/scr_h)
    return x, y
end

--\\  X,Y     
function angle_to_direction(oangle)
	local yaw = oangle.y
	local pitch = oangle.x
	return vector():setHP(yaw,pitch):normalize()
end

--\\   float-    
function frandom(n1, n2)
	n1 = n1 * 10
	n2 = n2 * 10
	return (math.random(n1, n2) / 10)
end

local ltxBuffer = {}	-->      

--\\      
--	sec			- 
--	line 		- 
-- 	*mode		-  ,       ("str", "tbl1", "bol", "num", "numf")	
--	*ini_file	- ini-   ,     system.ltx  .   
-- :    \   -   ,     
--  .  .    .
function ltx(sec, line, mode, ini_file)
	if sec == nil then
		_abort(_SN, "ltx", "sec (%s)(%s)", tostring(line), tostring(mode))
	end
 
	if not ltxBuffer[sec] then
		ltxBuffer[sec] = {}
	end
	
	local result = ltxBuffer[sec][line]
	if result ~= nil then
		--*    !    
		if type(result) == "userdata" then
			return utils.vector_copy_by_val(result)
		end
		
		return result
	end -->       ,   1    
 
	local ini = ini_file or system_ini()
 
	if ltxExist(sec, line, ini) then
		if mode==nil or mode=="numf" then   -->   
			ltxBuffer[sec][line] = ini:r_float(sec, line)
			return ltxBuffer[sec][line]
		end
		
		if mode=="bol" then	--> true\false
			ltxBuffer[sec][line] = ini:r_bool(sec, line)
			return ltxBuffer[sec][line]
		end
		
		if mode=="num" then   -->  
			ltxBuffer[sec][line] = ini:r_u32(sec, line)
			return ltxBuffer[sec][line] 	 
		end

		if mode=="str" then	--> 
			ltxBuffer[sec][line] = ini:r_string(sec, line)
			return ltxBuffer[sec][line] 	 
		end
		
		if mode=="vec" then	--> 
			local vec = ini:r_vector(sec, line)
			ltxBuffer[sec][line] = vec
			--return ltxBuffer[sec][line] 	 -->   
			return utils.vector_copy_by_val(ltxBuffer[sec][line])
		end
		
		if mode=="tbl1" then -->      (1 = ..., 2 = ....)
			local temp = ini:r_string(sec, line)
			ltxBuffer[sec][line] = string_expl(temp, ",")
			return ltxBuffer[sec][line] 	 
		end		
	end
	
	-- mDbg(_SN, "ltx - no section: "..sec.." || "..line)
	return nil
end


--\\         
function ltxBufferW(sec, line, value)
	if not ltxBuffer[sec] then
		   ltxBuffer[sec] = {}
	end

	ltxBuffer[sec][line] = value
end

--\\      
--	sec -    
function ltxItem(sec)
	local name  = ltx(sec, "inv_name", "str") or ""
	local descr = ltx(sec, "description", "str") or ""

	return xml(name), xml(descr)
end

--\\ ,    -*   
--	sec			- 
--	*line 		- 
--	*ini_file	- ini-   ,     system.ltx  .   
function ltxExist(sec, line, ini_file)
	local ini = ini_file or system_ini()
	if sec == nil then _abort(_SN, "ltxExist", "sec") end
	if not ini:section_exist(sec) then return false end
	if line and not ini:line_exist(sec, line) then return false end
	-- printf("SWMtrue")
	return true
end

--\\  <text>   xml-
--	xml_id	-  
function xml(xml_id)
	return game.translate_string(xml_id) 
end

--\\         custom data
--[[
	local value = 123
	local cd = {}
	cd["test"] = {}
	cd["test"]["string"] = ""	
	cd["test"]["line"] = value
	cd["test"]["simple_table"] = {2,4,6,8}
	cd["test"]["extended_table"] = {val1 = 1, val2 = 2, val3 = 3}	
	
	[test]
	string
	line = 123
	simple_table = 2468
	extended_table = val1, 1, val2, 2, val3, 3	
]]

function tocdata(tTbl)
	local g_pairs = pairs
	local g_tostring = tostring
	local _result_parts = {}
	for sec, tData in g_pairs(tTbl) do
		_result_parts[#_result_parts+1] = "\n["..sec.."]\n"
		if type(tData) ~= "table" then
			_abort(_SN, "tocdata", "tData is not table! result = %s, tData = %s", result, g_tostring(tData))
		else
			for line, t_Param in g_pairs(tData) do
				if t_Param == "" then 
					result = result..g_tostring(line).."\n"
				else
					result = result..g_tostring(line).." = "	
					if type(t_Param) == "table" then
						if table_size(t_Param) > 0 and #t_Param > 0 then
						--*     ,    
							for _,p1 in g_pairs(t_Param) do
								local first = true						
								if first then
									result = result..g_tostring(p1)
									first = false
								else
									result = result..", "..g_tostring(p1)
								end				   
							end	
						else
						--* -,     
							local first = true
							for p1,p2 in g_pairs(t_Param) do
								if first then
									result = result..g_tostring(p1)..", "..g_tostring(p2)
									first = false
								else
									result = result..", "..g_tostring(p1)..", "..g_tostring(p2)
								end				   
							end					
						end				
						result = result.."\n"
					else
						result = result..g_tostring(t_Param).."\n"
					end
				end
			end			
		end
	end
	local result = table.concat(_result_parts)
	
	return result
end

--\\          = 
function collect_sections(ini, sec)
	local r = {}
	if ini:section_exist(sec) then
		local n = ini:line_count(sec)
		if n > 0 then
			for i = 0,n-1 do
				local res,id,val = ini:r_line(sec,i,"","")
				if r[id] == nil then
					r[id] = val
				end
			end
		end
	end
	return r
end

--\\      
function _abort(script_name, function_name, error_string, ...)
	if script_name == nil then
	   script_name = "<nil>"
	end
	
	if function_name == nil then
	   function_name = "<nil>"
	end
	
	abort("%s.%s - "..error_string, script_name, function_name, ...)
end

--\\   
function log(text)
	if _console == nil or (_console.GetVal("dbg.log") == true) then
		get_console():execute("load ~~ " .. tostring(text))
	end
end

--\\  -    (-   1 )
function table_size(tTbl)
	local count = 0
	for _,_ in pairs(tTbl) do
		count = count + 1
	end
	
	return count
end

--! :      ""  ( #)    
function string_expl(sStr, sDiv, Mode, bNoClear)
  sStr = tostring(sStr)
  if not (sStr ~= "nil" and sStr ~= '') then return {} end -->  
  local tRet = {}
  local sPattern = '[%w%_]+' -->   (  '')
  if type(sDiv) == "string" then -->   :   
    if bNoClear then -->    ' '
      sPattern = '([^'..sDiv..']+)'
    else -->    
      sPattern = '%s*([^'..sDiv..']+)%s*'
    end
  end
  --*    
  if Mode == nil then -->  
    for sValue in sStr:gmatch(sPattern) do
      tRet[#tRet+1] = sValue
    end
  else
    local sTypeMode = type(Mode)
    if sTypeMode == "boolean" then -->  '[] = true  false'
      for sValue in sStr:gmatch(sPattern) do
        tRet[sValue] = Mode
      end
    elseif sTypeMode == "number" then -->  '[idx] =   '
      for sValue in sStr:gmatch(sPattern) do
        tRet[#tRet+1] = tonumber(sValue) or sValue
      end
    end
  end
  return tRet -->  
end

--*     cam_dir:getH()
--  ,       _
function calc_Y(new, old)
	local math_abs = math.abs
	local wL = 0
	local wR = 0
				
	if new < old then
		wR = old - new
		if new < 0 then
			wL = math_abs(-1.6 - new) + (4.8 - old)
		else
			wL = new + 1.6  + (4.8 - old)
		end
	else
		wL = new - old
		if old < 0 then
			wR = (4.8 - new) + math_abs(-1.6 - old)
		else
			wR = (4.8 - new) + math_abs(-1.6) + old
		end				
	end
				
	if wL < wR then
		return wL
	end
	if wL > wR then
		return -wR
	end
			
	return 0
end

--        x,z,y (P,B,H)
-- ,      
--     Wild Magic 5
function extract_euler_xzy(m)
	local math_atan2 = math.atan2
	if m.i.y < 1 then
		if m.i.y > -1 then
			local az = math.asin(-m.i.y)
			local ax = math_atan2(m.k.y, m.j.y)
			local ay = math_atan2(m.i.z, m.i.x)
			return ax, az, ay
		else
			local az = math.pi / 2
			local ax = -math_atan2(-m.k.x, m.k.z)
			local ay = 0
			return ax, az, ay
		end
	else
		local az = -math.pi / 2
		local ax = math_atan2(-m.k.x, m.k.z)
		local ay = 0
		return ax, az, ay
	end
end

function extract_direction(ph_element)
	local m		= ph_element:global_transform()
	local p,b,h = extract_euler_xzy(m)
	return vector():setHP(h, p)
end

--\\  ,      ID\Server OBJ
function getMapName(id_or_sobj)
	local sobj

	if type(id_or_sobj) == "number" then
		sobj = alife():object(id_or_sobj)
	else
		sobj = id_or_sobj
	end

	if sobj then
		local lvert = game_graph():vertex(sobj.m_game_vertex_id)
		local lid	= lvert:level_id()
		
		if lid ~= nil then
			return alife():level_name(lid)
		end
	end
end

--\\    (  ,  ()   ) 
local rang_num_to_name = {
			[0]		=	"st_rang_zero",
			[1]		=	"st_rang_novice",
			[2]		=	"st_rang_experienced",
			[3]		=	"st_rang_experienced",
			[4]		=	"st_rang_veteran",
			[5]		=	"st_rang_master",			
		}
						
function rang(obj)
	local rank = 0
	local obj_rank = obj:rank()
		
	if obj_rank >=0 and obj_rank <=25 then	--> novice
		rank = 1
	end

	if obj_rank >=26 and obj_rank <=30 then --> ext 1
		rank = 2
	end


	if obj_rank >=31 and obj_rank <=40 then --> ext 2
		rank = 3
	end


	if obj_rank >=41 and obj_rank <=50 then --> veteran
		rank = 4
	end

	if obj_rank >=51 then					--> master
		rank = 5
	end
			
	--[[ CS 1.5.10
	if obj_rank >= 0 and obj_rank <= 300 then
		rank = 1	-- Novice
	end

	if obj_rank >  300 and obj_rank <=  450 then
		rank = 2	-- Extnd. 1
	end

	if obj_rank >  450 and obj_rank <= 600 then
		rank = 3	-- Extnd. 2
	end
			
	if obj_rank >  600 and obj_rank <  900 then
		rank = 4	-- Veteran
	end

	if obj_rank >= 900 then
		rank = 5	-- Master
	end		
	]]
		
	return rank, obj_rank, rang_num_to_name[rank]
end
