function on_mcm_load()
  return { id="weapon", sh=true, gr={   
      { id="header", type="slide", link="ui_options_slider_economy_diff", text="ui_mcm_dph_loot_cond_weapon", size= {512,50}, spacing=20 },
      -- zombied
      { id="zombied_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_zombied_header", },
      { id="zombied_min", type="track", val=2, min=1, max=100, step=1, def=5 },
      { id="zombied_max", type="track", val=2, min=1, max=100, step=1, def=20 },
      -- novice
      { id="divider", type="line" },
      { id="novice_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_novice_header", },
      { id="novice_min", type="track", val=2, min=1, max=100, step=1, def=5 },
      { id="novice_max", type="track", val=2, min=1, max=100, step=1, def=20 },
      -- trainee
      { id="divider", type="line" },
      { id="trainee_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_trainee_header", },
      { id="trainee_min", type="track", val=2, min=1, max=100, step=1, def=5 },
      { id="trainee_max", type="track", val=2, min=1, max=100, step=1, def=25 },
      -- experienced
      { id="divider", type="line" },
      { id="experienced_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_experienced_header", },
      { id="experienced_min", type="track", val=2, min=1, max=100, step=1, def=5 },
      { id="experienced_max", type="track", val=2, min=1, max=100, step=1, def=30 },
      -- professional
      { id="divider", type="line" },
      { id="professional_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_professional_header", },
      { id="professional_min", type="track", val=2, min=1, max=100, step=1, def=10 },
      { id="professional_max", type="track", val=2, min=1, max=100, step=1, def=30 },
      -- veteran
      { id="divider", type="line" },
      { id="veteran_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_veteran_header", },
      { id="veteran_min", type="track", val=2, min=1, max=100, step=1, def=10 },
      { id="veteran_max", type="track", val=2, min=1, max=100, step=1, def=35 },
      -- expert
      { id="divider", type="line" },
      { id="expert_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_expert_header", },
      { id="expert_min", type="track", val=2, min=1, max=100, step=1, def=15 },
      { id="expert_max", type="track", val=2, min=1, max=100, step=1, def=35 },
      -- master
      { id="divider", type="line" },
      { id="master_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_master_header", },
      { id="master_min", type="track", val=2, min=1, max=100, step=1, def=15 },
      { id="master_max", type="track", val=2, min=1, max=100, step=1, def=40 },
      -- legend
      { id="divider", type="line" },
      { id="legend_header", clr={200, 200, 255, 200}, type="desc", text="ui_mcm_dph_loot_cond_weapon_legend_header", },
      { id="legend_min", type="track", val=2, min=1, max=100, step=1, def=20 },
      { id="legend_max", type="track", val=2, min=1, max=100, step=1, def=45 },
  }}, "dph_loot_cond"
end