----Trader shit

local trade_table = {

	["bandit"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["dolg"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["ecolog"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["freedom"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["killer"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["army"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["monolith"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["greh"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["stalker"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["csky"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["isg"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
	["renegade"] = {
		[1] = {
			["ground_coffee"] = 2
		},
	},
}

function drug_overdose(npc)
    local is_supplier = trader_autoinject.get_trader_type(npc) == trader_autoinject.SUPPLIER
    local is_barman = trader_autoinject.get_trader_type(npc) == trader_autoinject.BARMAN
    local is_medic = trader_autoinject.get_trader_type(npc) == trader_autoinject.MEDIC
    if is_supplier or is_barman or is_medic then
        local community = npc:character_community() or "stalker"
        local trader_table = trade_table[community] or trade_table["stalker"]
        local supply_level = clamp(trader_autoinject.supply_level(npc, true) or 1, 1, 3)

        if trader_table[supply_level] then
            trader_autoinject.spawn_items(npc, trader_table[supply_level], true)
        end
    end
end

TraderAuto = trader_autoinject.update

function trader_autoinject.update(npc)
    TraderAuto(npc)
    drug_overdose(npc)
end

----Dead body shit

local loot_table = {

	["bandit"] = {
		[1] = "ground_coffee",
	},
	["dolg"] = {
		[1] = "ground_coffee",
	},
	["ecolog"] = {
		[1] = "ground_coffee",
	},
	["freedom"] = {
		[1] = "ground_coffee",
	},
	["killer"] = {
		[1] = "ground_coffee",
	},
	["army"] = {
		[1] = "ground_coffee",
	},
	["monolith"] = {
		[1] = "ground_coffee",
	},
	["greh"] = {
		[1] = "ground_coffee",
	},
	["stalker"] = {
		[1] = "ground_coffee",
	},
	["zombied"] = {
		[1] = "ground_coffee",
	},
	["csky"] = {
		[1] = "ground_coffee",
	},
	["isg"] = {
		[1] = "ground_coffee",
	},
	["renegade"] = {
		[1] = "ground_coffee",
	},
	
}

local rank_table = {
	["novice"] 			= 0.00,
	["trainee"] 		= 0.00,
	["experienced"] 	= 0.01,
	["professional"] 	= 0.01,
	["veteran"] 		= 0.01,
	["expert"] 			= 0.01,
	["master"] 			= 0.01,
	["legend"] 			= 0.01,
}

local sections_table = {
	[1] = "ground_coffee",
}

function npc_drug_overdose(npc, npc_rank, npc_comm)
    -- local comm = npc_comm or "stalker"
    -- local looting_table = loot_table[comm] or loot_table["stalker"]
    -- local random_k = looting_table[math.random(1, #looting_table)]
    -- local sec_to_spawn = random_k[1] or "item_1"
    -- local chance = random_k[3] or 0.5

    if (math.random() < rank_table[npc_rank] ) then
        alife_create_item("ground_coffee", npc, {uses = 1})
    end

end

SpawnCosmetics = death_manager.spawn_cosmetics

function death_manager.spawn_cosmetics(npc, npc_id, npc_comm, npc_rank, visual, rand_condition)
    SpawnCosmetics(npc, npc_id, npc_comm, npc_rank, visual, rand_condition)
    npc_drug_overdose(npc, npc_rank, npc_comm)
end