local settings = dup_table(magnifier_switch_mcm.defaults)

local function printdebug(str, ...)
  if settings.debug then printf("[magnifier_switch] "..str, ...) end
end

local config_filename = [[items\settings\magnifier_switch_mappings.ltx]]
local mcm_keybinds = ui_mcm and ui_mcm.key_hold and true
local wpn_name
local suppress_mwheel
local mag_table, mag_table_inv
local unique_mappings, unique_mappings_inv

function init()
  local ini = ini_file_ex(config_filename)
  mag_table = ini:collect_section("magnifier_mappings")
  mag_table_inv = invert_table(mag_table)
  unique_mappings = ini:collect_section("unique_mappings")
  unique_mappings_inv = invert_table(unique_mappings)
end

function check_ME_version(required)
  local ver = (MODDED_EXES_VERSION or (get_modded_exes_version and get_modded_exes_version()) or 0)
  return required <= ver
end

--state (to switch to): 0 (switch magnifier off), 1 (switch magnifier on), nil (switch current state)
function get_new_section(sec, state)
  local new_section = (not (state == 0) and unique_mappings[sec]) or (not (state == 1) and unique_mappings_inv[sec])
  if new_section and ini_sys:section_exist(new_section) then
    printdebug("get_new_section | unique mapping found for section %s: %s", sec, new_section)
    return new_section
  end

  local base_sec = ini_sys:r_string_ex(sec, "parent_section")
  local scope_sec = base_sec and sec:sub(#base_sec+2)
  printdebug("get_new_section | sec: %s, base_sec: %s, scope_sec: %s", sec, base_sec, scope_sec)
  if not scope_sec then return end

  local new_scope = (not (state == 0) and mag_table[scope_sec]) or (not (state == 1) and mag_table_inv[scope_sec])
  new_section = new_scope and (base_sec.."_"..new_scope)
  if new_section and ini_sys:section_exist(new_section) then
    printdebug("get_new_section | new section: %s", new_section)
    return new_section
  end
end

function cancel_show_anm(anm_table, obj, owner)
  local owner_id = owner and owner:id()
  local obj_name = obj and obj:name()
  printdebug("cancel_show_anm | obj: %s, anm_name: %s", obj_name, anm_table.anm_name)

  if (owner_id == AC_ID) and obj and (obj_name == wpn_name) and anm_table.anm_name:startswith("anm_show") then
    anm_table.anm_name = "anm_idle"..anm_table.anm_name:sub(9)
    obj:switch_state(0)
  end
end

local ME_volume_mult = check_ME_version(20250819)
function cancel_show_sound(alias, parent, result)
  if parent and parent:id() == AC_ID and alias and alias:find("sndShow") then
    if ME_volume_mult then
      result.volume_mult = 0
    else --me when older modded exes
      result.section = "base_sounds"
      result.line = "snd_draw"
    end
  end
end

function switch_magnifier(wpn, sec, new_sec)
  wpn = wpn or db.actor:active_item()
  if not (wpn and wpn:cast_Weapon()) then return end

  if wpn:weapon_in_grenade_mode() then return wpn:switch_state(9) end

  sec = sec or wpn:section()
  new_sec = new_sec or get_new_section(sec)
  if not new_sec or (new_sec == sec) then return end

  local active_slot = db.actor:active_slot()
  local item_in_base_slot = db.actor:item_in_slot(3) and true
  local keep_aim_toggled = (settings.keep_aim_toggle
    and axr_main.weapon_is_zoomed and get_console():get_bool("wpn_aim_toggle"))

  local se_obj = alife_object(wpn:id())
  local new_wpn = se_obj and alife_clone_weapon(se_obj, new_sec)

  if new_wpn then
    local new_id = new_wpn.id
    wpn_name = new_wpn:name()
    suppress_mwheel = true
    printdebug("switch_magnifier | weapon successfully cloned: %s", wpn_name)

    nextTick(function()
      local obj = get_object_by_id(new_id)
      if not (obj and obj:name() == wpn_name) then return true end

      if active_slot == 2 and item_in_base_slot then
        db.actor:move_to_slot(obj, active_slot)
        nextTick(function() db.actor:activate_slot(active_slot) return true end, 2)
      end

      if keep_aim_toggled then
        CreateTimeEvent("magnifier_switch", "keep_aim", 0.08, function()
          level.press_action(bind_to_dik(key_bindings.kWPN_ZOOM))
          printdebug("toggled aim")
          return true
        end)
      end
      return true
    end, 2)

    RegisterScriptCallback("actor_on_hud_animation_play", cancel_show_anm)
    RegisterScriptCallback("on_before_play_hud_sound", cancel_show_sound)
    CreateTimeEvent("magnifier_switch", "unregister_anm_cancel", 0.1, function()
      printdebug("switch_magnifier | unregistering temp callbacks")
      UnregisterScriptCallback("actor_on_hud_animation_play", cancel_show_anm)
      UnregisterScriptCallback("on_before_play_hud_sound", cancel_show_sound)
      wpn_name = nil
      suppress_mwheel = false
      return true
    end)

	  return new_wpn
  end
end

local no_recursion = false
function delay_aimmode_toggle()
  no_recursion = true
  local func_bind = bind_to_dik(key_bindings.kWPN_FUNC)
  level.press_action(func_bind)
  level.release_action(func_bind)
  no_recursion = false
end

function on_before_key_press(key, bind, dis, flags)
  if no_recursion then return end
  if (key == settings.switch_bind) and actor_menu.is_hud_free() then
    if not mcm_keybinds then return switch_magnifier() end
    if not ui_mcm.get_mod_key(settings.modifier) then return end

    local wpn = db.actor:active_item()
    local sec = wpn and wpn:section()
    local new_sec = sec and get_new_section(sec)
    if not new_sec then return end

    local allow_key = bind ~= key_bindings.kWPN_FUNC
    flags.ret_value = allow_key

    local mode = settings.press_type
    if mode == 0 then
      --return ui_mcm.simple_press("magnifier_switch_bind", key, switch_magnifier)
      flags.ret_value = not switch_magnifier(wpn, sec, new_sec)
      return
    elseif mode == 1 then
      if ui_mcm.double_tap("magnifier_switch_bind", key) then
        flags.ret_value = not switch_magnifier(wpn, sec, new_sec)
      end
    end

    ui_mcm.simple_press("magnifier_switch_aimmode", key, delay_aimmode_toggle)
  end
end

function on_key_hold(key)
  if mcm_keybinds
  and (settings.press_type == 2)
  and (key == settings.switch_bind)
  and actor_menu.is_hud_free()
  and ui_mcm.get_mod_key(settings.modifier) then
    if ui_mcm.key_hold("magnifier_switch_bind", key) then
      switch_magnifier()
    end
  end
end

function on_mouse_wheel(dir, flags)
  if suppress_mwheel then
    flags.ret_value = false
    return
  end

  if not actor_menu.is_hud_free() then return end

  local wpn = db.actor:active_item()
  local sec = wpn and wpn:section()
  if not (sec and (not settings.mwheel_switch_ads_only or axr_main.weapon_is_zoomed)) then return end

  local zoom_inverted = get_console():get_bool("mouse_wheel_invert_zoom")
  local next_state = zoom_inverted and ((dir == 1 and 0) or (dir == 0 and 1)) or dir
  local new_sec = sec and next_state and get_new_section(sec, next_state)
  printdebug("on_mouse_wheel | zoom_inverted: %s, next_state: %s", zoom_inverted, next_state)
  if new_sec then
    flags.ret_value = not switch_magnifier(wpn, sec, new_sec)
  end
end

function on_option_change(mcm)
  if mcm then
    for k, v in pairs(magnifier_switch_mcm.defaults) do
      settings[k] = ui_mcm.get("magnifier_switch/" .. k)
      if settings[k] == nil then settings[k] = v end
    end

    printdebug("on_option_change | use_mousewheel: %s", tostring(settings.use_mousewheel))
    if settings.use_mousewheel then
      UnregisterScriptCallback("on_before_key_press", on_before_key_press)
      UnregisterScriptCallback("on_key_hold", on_key_hold)
      RegisterScriptCallback("on_mouse_wheel", on_mouse_wheel)
    else
      RegisterScriptCallback("on_before_key_press", on_before_key_press)
      RegisterScriptCallback("on_key_hold", on_key_hold)
      UnregisterScriptCallback("on_mouse_wheel", on_mouse_wheel)
    end
  end
end

og_play_item_sound = itms_manager.play_item_sound
itms_manager.play_item_sound = function(item, vol)
  if settings.switch_sound and item and item:name() == wpn_name then
    local snd = sound_object("interface\\magnifier_flip")
    if snd then snd:play(db.actor, 0, sound_object.s2d) end
    return
  end
  og_play_item_sound(item, vol)
end

--[[og_gpc = item_parts.get_parts_con
item_parts.get_parts_con = function(obj, id, eval)
  return og_gpc(obj, id, eval) or {}
end]]

function on_game_start()
  init()
  --RegisterScriptCallback("on_before_key_press", on_before_key_press)
  --RegisterScriptCallback("on_key_hold", on_key_hold)
  --RegisterScriptCallback("on_mouse_wheel", on_mouse_wheel)
  RegisterScriptCallback("on_option_change", on_option_change)
  on_option_change(mcm_keybinds)
end

function bind_dummy(obj)
  local sec = obj and obj:section()
  if not sec then return end

  local replace_sec = ini_sys:r_string_ex(sec, "replace_section") or mag_table[sec] or mag_table_inv[sec]
  if replace_sec and ini_sys:section_exist(replace_sec) then
    alife_create_item(replace_sec, db.actor)
  end
  alife_release(obj)
end
