function on_mcm_load()
    local op = {
        id = "roguelite",
        sh = true,
        gr = {
            {
                id = "title",
                type = "slide",
                link = "ui_options_slider_gameplay_diff",
                text = "ui_mcm_roguelite_title",
                size = {512,50},
                spacing = 20
            },    
            --Global Settings
            {
                id = "desc_mcm",
                type = "desc",
                text = "ui_mcm_roguelite_global_description",
                clr = {255, 255 ,255 ,0},
            },
            {
                id = "is_roguelite_enabled",
                type = "check",
                val = 1,
                def = true
            }
        }
    }

    local modules = roguelite_manager.get_modules()

    for _, module in pairs(modules) do
        if module.append_mcm_options then 
            module.append_mcm_options(op.gr)
        end
    end

    op.gr[#op.gr+1] = { id = "line" , type = "line" }
    op.gr[#op.gr+1] = {
        id = "desc_mcm",
        type = "desc",
        text = "ui_mcm_roguelite_debug_description",
        clr = {255, 255 ,255 ,0},
    }
    op.gr[#op.gr+1] = {
        id = "debug",
        type = "check",
        val = 1,
        def = false
    };

    return op
end

function get_config(key, default_when_nil)
    local opt = ui_mcm and ui_mcm.get("roguelite/"..key)
    if opt == nil then
        opt = default_when_nil
    end
    return opt
end