siski = siski or {}
siski.switches = siski.switches or {}

local s = siski.switches

s.core = true
s.safe = true
s.log = true
s.config = true
s.bus = true
s.timers = true
s.board_index = true
s.memory = true
s.story_psy_watchdog = true
s.story_events = true
s.smart_tasks = true
s.tasks = true
s.mutants = true
s.base_filler = true
s.dynamic_bases = true
s.service_filler = true
s.axr_task_patch = true
s.npc_faction_override = true
s.debug_hud = true
