-- @ Version: SCREEN SPACE SHADERS - UPDATE 23
-- @ Description: Motion Blur script
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- Settings
local ssfx_motionblur_quality = 0

local ssfx_motionblur_intensity = 0
local ssfx_motionblur_onlyhud = 0
local ssfx_motionblur_cameraint = 0

-- Internal vars
module_installed = true

local function apply_motionblur_settings()

	-- Apply commands
	get_console():execute("ssfx_motionblur (" .. ssfx_motionblur_quality .. "," .. ssfx_motionblur_intensity .. ", " .. (ssfx_motionblur_onlyhud and 1 or 0) .. "," .. ssfx_motionblur_cameraint .. ")")

end

local function update_settings()
	
	-- Get settings
	module_id = "ssfx_pp/ssfx_motionblur"

	ssfx_motionblur_quality = ssfx_001_mcm.ssfx_get_setting(module_id, "quality", ssfx_pp_mblur_settings)
	ssfx_motionblur_intensity = ssfx_001_mcm.ssfx_get_setting(module_id, "intensity", ssfx_pp_mblur_settings)
	ssfx_motionblur_onlyhud = ssfx_001_mcm.ssfx_get_setting(module_id, "hudonly", ssfx_pp_mblur_settings)
	ssfx_motionblur_cameraint = ssfx_001_mcm.ssfx_get_setting(module_id, "camera", ssfx_pp_mblur_settings)

	-- Apply settings
	apply_motionblur_settings()

end

function on_game_start()

	-- General Functions
	RegisterScriptCallback("on_option_change", update_settings)

	-- Read and apply settigns
	update_settings()
end