-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets

	o["wpn_dtmdr"] = {
		y = 0.3,
        }

        o["wpn_dtmdr_black"] = {
 		y = 0.3,
        }
        o["wpn_dtmdr_sup"] = {
		y = 0.3,
        }
        o["wpn_dtmdr_black_sup"] = {
		y = 0.3,
        }
end