--[[
	=====================================================================
	Addon      : Tosox Mini Mods Repo: Stop Addon Log Spam
	Link       : https://www.moddb.com/mods/stalker-anomaly/addons/tosox-mini-mods-repo/
	Author     : Tosox
	Date       : 12.01.2024
	Last Edit  : 19.01.2024
	=====================================================================
--]]

-- Zatura Autostack
if zatura_autostack then
	zatura_autostack.printf = function(...) end
end

-- Custom Functor Autoinject
if custom_functor_autoinject then
	custom_functor_autoinject.printf = function(...) end
end

-- Food, Drug and Drink Animations
if ea_prefetcher then
	ea_prefetcher.printf = function(...) end
end

-- G.A.M.M.A. Close Quarter Combat
if grok_bo then
	grok_bo.printf = function(...) end
end

-- DLTX Minimodpack: More drop from drugs
if zz_itms_manager_more_drops_from_drugs then
	zz_itms_manager_more_drops_from_drugs.printf = function(...) end
end
